---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-operator
  namespace: flux-apps
spec:
  interval: 5m
  path: ./install
  prune: true
  sourceRef:
    kind: GitRepository
    name: operatorhub-io
  timeout: 1m
