---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: "*"
  targetNamespace: longhorn-system
  values:
    defaultSettings:
      v2DataEngine: true
      defaultDataPath: /dev/vg0
      defaultReplicaCount: 3
      storageMinimalAvailablePercentage: 10
      createDefaultDiskLabeledNodes: false
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
    longhornManager:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
    longhornDriver:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
  interval: 5m0s
