---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: olm
  namespace: olm
spec:
  chart:
    spec:
      chart: olm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudtooling
      version: 0.33.0
  values: {}
  interval: 5m0s
