---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix-homeserver
spec:
  chart:
    spec:
      chart: matrix-homeserver
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hauke-cloud
      version: "*"
  targetNamespace: matrix
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: matrix-values
      optional: true
  interval: 5m0s
